name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Adjust to your branch name

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub's Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Action to checkout your repository

      - name: Install Dependencies
        run: |
          npm install

      - name: Start Application
        run: |
          npm start
